sudo: false
language: python
python:
  - 3.5
install:
  - pip install tox
  - pip install coveralls
  #- pip install -r requirements.txt
# command to run tests
env:
  - $COVPYYAML=cov41-pyyaml,coveralls41
script:
  #- pytest # or py.test for Python versions 3.5 and below
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$COVPYYAML
notifications:
  email: false