sudo: false

language: python

python:
  - 3.5

install:
  - pip install tox
  - pip install coveralls
  - pip install pylint
  - pip install -r requirements.txt

env:
  - $COVPYYAML=cov41-pyyaml,coveralls41

script:
  - pylint main.py
  - python -m unittest discover -v

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
