# Setup
theme: jekyll-theme-cayman

title:        Text Mining Challenge
tagline:      A data science project

author:
  name:       Edouard Mehlman
  url:        edouard.mehlman@polytechnique.edu

collections:
  documentation:
    output: true
    permalink: /:collection/:name # This is just display
