theme: jekyll-theme-cayman
#
#defaults:
#  -
#    scope:
#      path: ""
#      type: "pages"
#    values:
#      layout: "page"
#      comments: true
#      search: true
#      sidebar: home_sidebar
#      topnav: topnav
#  -
#    scope:
#      path: ""
#      type: "tooltips"
#    values:
#      layout: "page"
#      comments: true
#      search: true
#      tooltip: true
#
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      comments: true
#      search: true
#      sidebar: home_sidebar
#      topnav: topnav
#
## these are defaults used for the frontmatter for these file types
#
#sidebars:
#- mydoc_sidebar
